doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                mapping_types:
                    enum: string
            login:
                url: '%env(resolve:DATABASE_URL_LOGIN)%'
                mapping_types:
                    enum: string
        types:
            enum_access: App\Type\EnumAccessType

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                auto_mapping: true
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Game:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Game
            login:
                connection: login
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Login:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: Login
                    JMSPaymentCoreBundle:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/config/packages/JMSPaymentCoreBundle'
                        prefix: JMS\Payment\CoreBundle\Entity
                        alias: JMSPaymentCoreBundle